### ISSUE TITLE
how to test on my own images?

### ISSUE THREAD

**Issue by ningbende** [JingyunLiang/FKP#1]
hi Jingyun,
   Thanks for your work. There are too many test code in the project which make me confuesd.
I just want to test on my own image, what should do ? 
Thanks again.

**Comment by JingyunLiang** [comment]
If you want to test on synthesized images, please follow the `README.md`. Taking Set5 as an example, please first generate (HR, LR, kernel) triplets by `python prepare_dataset.py --model DIPFKP --sf 2 --dataset Set5` and then test the model  by `python main.py --SR --sf 2 --dataset Set5`. You may need to organize your images as `./data/datasets/Set5/HR/baby.png`.

If you want to test on real images without ground-truth kernels, just put your images in `./data/datasets/Set5/DIPFKP_lr_x4` and run `python main.py --SR --sf 4 --dataset Set5 --real`.

**Comment by ningbende** [comment]
Thanks a lot!
