### ISSUE TITLE
about random kernel generator

### ISSUE THREAD

**Issue by zhihongp** [JingyunLiang/FKP#2]
In the following code, lamda_1&2 (referred as kernel width) are used to calculate the COV matrix.  But shouldn't the square of lambda be used here for covariance?

https://github.com/JingyunLiang/FKP/blob/5ca3f7c39ba849408993cec64341e2639063984f/data/prepare_dataset.py#L50

**Comment by JingyunLiang** [comment]
Here, `lambda_1` and `lambda_2` denote `$\sigma_1^2$` and `$\sigma_2^2$` in the covariance matrix, respectively. Therefore, it has already been squared. Note that isotropic Gaussian generation functions often take `$\sigma$` (the standard deviation, not squared) as input.

We did this to be consistent with [mvnpdf](https://www.mathworks.com/help/stats/mvnpdf.html#d123e578251)(anisotropic Gaussian) and [fspecial](https://www.mathworks.com/help/images/ref/fspecial.html#d123e83687)(isotropic Gaussian) in Matlab.
