### ISSUE TITLE
Pixel Offset Problem

### ISSUE THREAD

**Issue by jiandandan001** [JingyunLiang/FKP#4]
Hi, thank you for sharing the code.

I have an LR image and corresponding HR image.

We use the LR  image as the input to the KernelGAN-FKP, and obtain a super-resolved image without ground-truth kernels, .

It seems that there is pixel offset between the super-resolved image and the original HR image, leading to a very low PSNR of the super-resolved image.

Do you know how to solve this problem?

**Comment by JingyunLiang** [comment]
Feel free to open it if you have more questions.
