### ISSUE TITLE
Benchmark Evaluation on KernelGANFKPx4

### ISSUE THREAD

**Issue by royson** [JingyunLiang/FKP#5]
Hello,

Thanks for uploading the code.

I am trying to evaluate KernelGANFKP on Set5 & Set14 & B100 for scaling factor x4:
`FKP/KernelGANFKP$ python main.py --SR --sf 4 --dataset {dataset}`

However, I am hitting an error during the forward pass of the discriminator if the input patch has a height or width < 27. Is KernelGANFKPx4 not supported for Set5, Set14, and B100 datasets?

**Comment by JingyunLiang** [comment]
KernelGAN is not suitable for small images by design. You can adjust the crop size here
https://github.com/JingyunLiang/FKP/blob/127c12103ebbfca7b4a6cf4f03c0c44dd24c10bb/KernelGANFKP/config/configs_FKP.py#L27
but it will leads to bad performance.
